name:                aws-lambda-haskell-url-shortener
version:             0.1.0
github:              "fcracker79/aws-lambda-haskell-url-shortener"
license:             MIT
author:              "Mirko Bonasorte"
maintainer:          "fcracker79@gmail.com"
copyright:           "2020 Mirko Bonasorte"

description:         Please see the README on GitHub at <https://github.com/fcracker79/aws-lambda-haskell-url-shortener#readme>

build-tools:
- hspec-discover
dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime
- amazonka
- amazonka-dynamodb
- amazonka-ssm
- aeson
- bytestring
- lens
- resourcet
- text
- unordered-containers
- monad-control
- base
- conduit
- conduit-extra
- exceptions
- lens
- random-strings
- semigroups
- text
- time
- transformers
- unordered-containers
- unliftio-core
- monad-loops
- http-types
- req
- http-client
- http-api-data

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -static
    - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - aws-lambda-haskell-url-shortener

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
  - FlexibleContexts
  - DeriveAnyClass

tests:
  unit-test-aws-lambda-haskell-url-shortener:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit
      - aws-lambda-haskell-url-shortener
      - test-framework
      - test-framework-hunit
      - hspec
  integration-test-aws-lambda-haskell-url-shortener:
    main: Spec.hs
    source-dirs: test/integration
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit
      - aws-lambda-haskell-url-shortener
      - test-framework
      - test-framework-hunit
      - hspec
      - amazonka-core
